---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      interpreter_python: auto_silent
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  log: true
  inventory:
    directory: ./inventory
platforms:
  - name: resolute
    image_url: "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img"
    image_name: resolute
    ssh_user: ubuntu
    ssh_user_group: sudo
    ssh_port: 22401
    memory: 2048
    cpus: 2
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
